#!/usr/bin/env python3
""" jdiff is a program for finding the difference between 2 json structures. 

The MIT License (MIT)
Copyright (c) 2021 Timothy Norman Murphy <tnmurphy@gmail.com>
Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions: The
above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.  THE SOFTWARE IS PROVIDED
"AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

It's not perfect!  It detects differences between maps/dictionaries but
not between lists.  e.g. if the top level items to compare are [ 1, 2,
3 ] and [ 1, 2, 5 ] then it will see that they are not equal but not be
able to show that 3 should be removed and 5 added to - i.e. it cannot
gernerate diffs on lists.
"""

import sys,os
import json
import re
import jdiff



if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="compare files containing JSON")
    parser.add_argument("files", metavar="Files", nargs='*', 
             help="list of files to compare. Changes listed from the first file to each of the others")
    parser.add_argument("-l", action="store_true", 
             help="line mode - look for the first 2 complete json strings in the standard input and compare them")
    args = parser.parse_args()

    if args.l:
        jdiff.line_diff()
    elif len(args.files) < 3:
        jdiff.file_diff(args.files)
    else:
        sys.stderr.write("jdiff either needs 2 files or the -l option for line mode\n")
        sys.exit(1)

